---
- hosts: all

  become: true

  vars_files:
    - vars/default.yml

  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes

    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Add user to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
