---
- hosts: all

  become: true

  tasks:
    - name: Upgrade OS
      apt:
        upgrade: dist

    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Update packages
      apt:
        name: "*"
        state: latest
